<?php
class UG_GitHub_API {
    private $token;
    private $username;
    private $repo;
    private $api_url = 'https://api.github.com';
    private $branch = 'main';
    private $is_private = false;
    private $pages_url = '';
    private $upload_path = '';
    
    public function __construct($token, $username, $repo, $is_private = false, $upload_path = '') {
        $this->token = $token;
        $this->username = $username;
        $this->repo = $repo;
        $this->is_private = $is_private;
        $this->upload_path = trim($upload_path, '/');
        $this->pages_url = 'https://' . $username . '.github.io';
    }
    
    public function test_connection() {
        $url = $this->api_url . '/user';
        $response = $this->make_request('GET', $url);
        
        if ($response && isset($response['login'])) {
            return array(
                'success' => true,
                'message' => $response['login']
            );
        }
        
        return array(
            'success' => false,
            'message' => isset($response['message']) ? $response['message'] : __('Authentication failed', 'upload-to-github')
        );
    }
    
    public function test_write_permission() {
        $test_file = 'test-wp-upload-' . time() . '.txt';
        $content = 'Test write permission at ' . current_time('mysql');
        
        $result = $this->upload_file($test_file, $content, 'Test write permission');
        
        if ($result['success']) {
            $this->delete_file($test_file, 'Delete test file');
            return array(
                'success' => true,
                'message' => __('Write permission verified', 'upload-to-github')
            );
        }
        
        return array(
            'success' => false,
            'message' => isset($result['message']) ? $result['message'] : __('Write permission denied', 'upload-to-github')
        );
    }
    
    public function repository_exists() {
        $url = $this->api_url . '/repos/' . $this->username . '/' . $this->repo;
        $response = $this->make_request('GET', $url);
        return $response && !isset($response['message']);
    }
    
    public function get_repository_info() {
        $url = $this->api_url . '/repos/' . $this->username . '/' . $this->repo;
        $response = $this->make_request('GET', $url);
        
        if ($response && isset($response['private'])) {
            return array(
                'visibility' => $response['private'] ? 'private' : 'public',
                'name' => $response['name'],
                'full_name' => $response['full_name'],
                'description' => isset($response['description']) ? $response['description'] : '',
                'created_at' => $response['created_at'],
                'updated_at' => $response['updated_at'],
                'default_branch' => isset($response['default_branch']) ? $response['default_branch'] : 'main',
                'has_pages' => isset($response['has_pages']) ? $response['has_pages'] : false
            );
        }
        
        return false;
    }
    
    public function readme_exists() {
        $path = 'README.md';
        $url = $this->api_url . '/repos/' . $this->username . '/' . $this->repo . '/contents/' . $path;
        $response = $this->make_request('GET', $url);
        
        return $response && !isset($response['message']);
    }
    
    public function create_readme() {
        $path = 'README.md';
        $url = $this->api_url . '/repos/' . $this->username . '/' . $this->repo . '/contents/' . $path;
        
        $readme_content = "# Upload to GitHub - WordPress Plugin\n\n";
        $readme_content .= "This repository is automatically managed by the **[Upload to GitHub](https://github.com/inject3r/upload-to-github)** WordPress plugin.\n\n";
        $readme_content .= "## About This Repository\n\n";
        $readme_content .= "- **Created by:** [Upload to GitHub](https://github.com/inject3r/upload-to-github) WordPress Plugin v" . UG_VERSION . "\n";
        $readme_content .= "- **Purpose:** Stores media files uploaded from WordPress\n";
        $readme_content .= "- **Auto-generated:** Do not edit manually\n\n";
        $readme_content .= "## Links\n\n";
        $readme_content .= "- **Plugin Repository:** [https://github.com/inject3r/upload-to-github](https://github.com/inject3r/upload-to-github)\n";
        $readme_content .= "- **WordPress Plugin:** [Upload to GitHub](https://wordpress.org/plugins/upload-to-github)\n\n";
        $readme_content .= "## Important\n\n";
        $readme_content .= "> **Do not modify files in this repository manually!**\n\n";
        $readme_content .= "All files are managed by the Upload to GitHub WordPress plugin. Manual changes may be overwritten.\n\n";
        $readme_content .= "---\n\n";
        $readme_content .= "*Generated by [Upload to GitHub](https://github.com/inject3r/upload-to-github) v" . UG_VERSION . " on " . current_time('Y-m-d H:i:s') . "*\n";
        
        $existing = $this->make_request('GET', $url);
        $sha = isset($existing['sha']) ? $existing['sha'] : null;
        
        $data = array(
            'message' => 'Add README.md via Upload to GitHub plugin v' . UG_VERSION,
            'content' => base64_encode($readme_content),
            'branch' => $this->branch
        );
        
        if ($sha) {
            $data['sha'] = $sha;
        }
        
        $response = $this->make_request('PUT', $url, $data);
        
        return $response && isset($response['content']);
    }
    
    public function create_repository($visibility = 'public', $description = '') {
        $url = $this->api_url . '/user/repos';
        $data = array(
            'name' => $this->repo,
            'private' => ($visibility === 'private'),
            'auto_init' => true,
            'description' => $description ?: sprintf(
                '[upload-to-github] v%s - This repository was created by the Upload to GitHub WordPress plugin',
                UG_VERSION
            )
        );
        
        $response = $this->make_request('POST', $url, $data);
        
        if ($response && isset($response['name'])) {
            $this->create_readme();
            
            if ($visibility === 'private') {
                $this->enable_github_pages();
            }
            return true;
        }
        
        return false;
    }
    
    public function update_repository_visibility($visibility) {
        $url = $this->api_url . '/repos/' . $this->username . '/' . $this->repo;
        $data = array(
            'private' => ($visibility === 'private')
        );
        
        $response = $this->make_request('PATCH', $url, $data);
        
        if ($response && isset($response['name'])) {
            $this->is_private = ($visibility === 'private');
            
            if ($this->is_private) {
                $this->enable_github_pages();
            }
            return true;
        }
        
        return false;
    }
    
    public function enable_github_pages() {
        $pages_repo = $this->username . '.github.io';
        $url = $this->api_url . '/repos/' . $this->username . '/' . $pages_repo;
        $response = $this->make_request('GET', $url);
        
        if (!$response || isset($response['message'])) {
            $create_url = $this->api_url . '/user/repos';
            $data = array(
                'name' => $pages_repo,
                'private' => false,
                'auto_init' => true,
                'description' => sprintf(
                    '[upload-to-github] v%s - GitHub Pages repository for media files',
                    UG_VERSION
                )
            );
            
            $this->make_request('POST', $create_url, $data);
        }
        
        $pages_url = $this->api_url . '/repos/' . $this->username . '/' . $this->repo . '/pages';
        $pages_data = array(
            'source' => array(
                'branch' => $this->branch,
                'path' => '/'
            )
        );
        
        $this->make_request('POST', $pages_url, $pages_data);
        
        return true;
    }
    
    public function upload_file($file_path, $content, $message = 'Upload via WordPress') {
        $path = 'uploads/' . $file_path;
        
        if (!empty($this->upload_path)) {
            $path = $this->upload_path . '/uploads/' . $file_path;
        }
        
        $url = $this->api_url . '/repos/' . $this->username . '/' . $this->repo . '/contents/' . $path;
        
        $existing = $this->make_request('GET', $url);
        $sha = isset($existing['sha']) ? $existing['sha'] : null;
        
        $data = array(
            'message' => $message . ' - ' . basename($file_path),
            'content' => base64_encode($content),
            'branch' => $this->branch
        );
        
        if ($sha) {
            $data['sha'] = $sha;
        }
        
        $response = $this->make_request('PUT', $url, $data);
        
        if ($response && isset($response['content'])) {
            $file_url = $this->get_file_url($response['content']['path']);
            
            return array(
                'success' => true,
                'url' => $file_url,
                'sha' => $response['content']['sha'],
                'path' => $response['content']['path']
            );
        }
        
        return array(
            'success' => false,
            'message' => isset($response['message']) ? $response['message'] : __('Upload failed', 'upload-to-github')
        );
    }
    
    public function delete_file($file_path, $message = 'Delete via WordPress') {
        $path = 'uploads/' . $file_path;
        
        if (!empty($this->upload_path)) {
            $path = $this->upload_path . '/uploads/' . $file_path;
        }
        
        $url = $this->api_url . '/repos/' . $this->username . '/' . $this->repo . '/contents/' . $path;
        
        $existing = $this->make_request('GET', $url);
        if (!$existing || !isset($existing['sha'])) {
            return array(
                'success' => false,
                'message' => __('File not found on GitHub', 'upload-to-github')
            );
        }
        
        $data = array(
            'message' => $message . ' - ' . basename($file_path),
            'sha' => $existing['sha'],
            'branch' => $this->branch
        );
        
        $response = $this->make_request('DELETE', $url, $data);
        
        if ($response && !isset($response['message'])) {
            return array(
                'success' => true,
                'message' => __('File deleted successfully', 'upload-to-github')
            );
        }
        
        return array(
            'success' => false,
            'message' => isset($response['message']) ? $response['message'] : __('Delete failed', 'upload-to-github')
        );
    }
    
    public function clear_repository() {
        $path = 'uploads';
        if (!empty($this->upload_path)) {
            $path = $this->upload_path . '/uploads';
        }
        
        $url = $this->api_url . '/repos/' . $this->username . '/' . $this->repo . '/contents/' . $path;
        $response = $this->make_request('GET', $url);
        
        if (!$response || isset($response['message'])) {
            return array(
                'success' => false,
                'message' => __('No uploads folder found or repository is empty.', 'upload-to-github')
            );
        }
        
        $deleted = 0;
        $errors = array();
        
        if (isset($response['tree']) && is_array($response['tree'])) {
            foreach ($response['tree'] as $item) {
                if ($item['type'] === 'blob') {
                    $result = $this->delete_file($item['path'], 'Clear repository via plugin');
                    if ($result['success']) {
                        $deleted++;
                    } else {
                        $errors[] = $item['path'] . ': ' . $result['message'];
                    }
                }
            }
        }
        
        return array(
            'success' => $deleted > 0 || empty($errors),
            /* translators: 1: number of deleted files, 2: error messages if any */
            'message' => sprintf(
                __('Cleared %1$d files from repository. %2$s', 'upload-to-github'),
                $deleted,
                !empty($errors) ? 'Errors: ' . implode(', ', $errors) : ''
            ),
            'deleted' => $deleted,
            'errors' => $errors
        );
    }
    
    private function get_file_url($path) {
        if ($this->is_private) {
            return $this->pages_url . '/' . $path;
        } else {
            return 'https://raw.githubusercontent.com/' . 
                   $this->username . '/' . 
                   $this->repo . '/' . 
                   $this->branch . '/' . 
                   $path;
        }
    }
    
    public function make_request($method, $url, $data = null) {
        $args = array(
            'method' => $method,
            'headers' => array(
                'Authorization' => 'token ' . $this->token,
                'Accept' => 'application/vnd.github.v3+json',
                'User-Agent' => 'WordPress-Upload-To-GitHub'
            ),
            'timeout' => 30
        );
        
        if ($data) {
            $args['body'] = json_encode($data);
            $args['headers']['Content-Type'] = 'application/json';
        }
        
        $response = wp_remote_request($url, $args);
        
        if (is_wp_error($response)) {
            return false;
        }
        
        $body = wp_remote_retrieve_body($response);
        return json_decode($body, true);
    }
}